// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWUto1wPq__i250mCkiWmXxJcdIy_gfsU',
    appId: '1:573154829762:web:8fcd6181de316bbe9e625b',
    messagingSenderId: '573154829762',
    projectId: 'cinova-show',
    authDomain: 'cinova-show.firebaseapp.com',
    storageBucket: 'cinova-show.appspot.com',
    measurementId: 'G-2B6W7YFGLM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjUx6feMXBWHaes_d9dH3TvhayccfhVBU',
    appId: '1:573154829762:android:40c97fe562cd8c309e625b',
    messagingSenderId: '573154829762',
    projectId: 'cinova-show',
    storageBucket: 'cinova-show.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDX2w4o7JU2bHCt5LTR_FLY-qUrFdVekhU',
    appId: '1:573154829762:ios:10c19deac6b074c99e625b',
    messagingSenderId: '573154829762',
    projectId: 'cinova-show',
    storageBucket: 'cinova-show.appspot.com',
    iosBundleId: 'com.example.projekweb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDX2w4o7JU2bHCt5LTR_FLY-qUrFdVekhU',
    appId: '1:573154829762:ios:40eceba27236078f9e625b',
    messagingSenderId: '573154829762',
    projectId: 'cinova-show',
    storageBucket: 'cinova-show.appspot.com',
    iosBundleId: 'com.example.projekweb.RunnerTests',
  );
}
